name: "SGCC Electricity"
version: "v1.6.5"
slug: "sgcc_electricity"
description: "获取国网电费数据的插件"
url: "https://github.com/ARC-MX/sgcc_electricity_new"
arch:
  - aarch64
  - amd64
host_network: true
startup: application
boot: auto
init: false
#image: "registry.cn-hangzhou.aliyuncs.com/arcw/sgcc_electricity-{arch}"
map:
  - addon_config:rw
  - homeassistant_config:rw
options:
  logins:
    phone: ""
    password: ""
  db_mode: Close
  sqlite:
    sqlite_db_name: "home-assistant_v2.db"
    sqlite_db_path: "homeassistant"
  mariadb:
    mariadb_url: "homeassistant.local"
    mariadb_port: 3306
    mariadb_user: "user"
    mariadb_password: "password"
    mariadb_db_name: "homeassistant"
  data_retention_days: "7"
  ha_sensor_enabled: false 
  has_sensor:
    hass_url: "http://homeassistant.local:8123/"
    hass_token: ""
  customize:
    job_start_time: "07:00"
    driver_implicity_wait_time: 60
    retry_times_limit: 5
    login_expected_time: 60
    retry_wait_time_offset_unit: 10
    log_level: "INFO"
    recharge_notify: false
    balance: 5.0
    pushplus_token: ""
schema:
  logins:
    phone: str
    password: str
  db_mode: list(Sqlite3|Mysql|Mariadb|Close)   
  sqlite:
    sqlite_db_name: str
    sqlite_db_path: str
  mariadb:
    mariadb_url: str
    mariadb_port: int
    mariadb_user: str
    mariadb_password: str
    mariadb_db_name: str
  data_retention_days: list(7|30) 
  ha_sensor_enabled: bool  
  has_sensor:
    hass_url: str
    hass_token: str
  customize:
    job_start_time: str
    driver_implicity_wait_time: int
    retry_times_limit: int
    login_expected_time: int
    retry_wait_time_offset_unit: int
    log_level: list(INFO|DEBUG) 
    recharge_notify: bool 
    balance: float 
    pushplus_token: "str?"
